server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location ~ (^|/)\. {
    return 404;
  }

  location ~* (^|/)(.*\.env.*|.*secret.*|.*credential.*|.*service-account.*|terraform\.tfvars|terraform\.tfstate|ecosystem\.config\.js|debug/vars)$ {
    return 404;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }

  location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|woff2?|otf)$ {
    expires 30d;
    add_header Cache-Control "public, immutable";
    try_files $uri =404;
  }
}
